# =============================================================================
# АВТОЗАПУСК
# =============================================================================
# Программы, запускающиеся при старте Hyprland
# (демоны уведомлений, статус-бары, обои и т.д.)

exec-once = hyprpaper
exec-once = ~/.config/quickshell/scripts/start.sh
exec-once = swaybg -i /home/graff/.config/hypr/walls/wall.jpg -m fill &
