# =============================================================================
# ВВОД (КЛАВИАТУРА, ТАЧПАД, МЫШЬ)
# =============================================================================
# Настройка устройств ввода
# Документация: https://wiki.hypr.land/Configuring/Variables/#input

input {
    kb_layout = us,ru
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

# ----------------------------------------------------------------------------
# ПЕРИФЕРИЙНЫЕ УСТРОЙСТВА
# ----------------------------------------------------------------------------
# Настройка для конкретных устройств
# Документация: https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
