# =============================================================================
# МОНИТОРЫ
# =============================================================================
# Настройка подключенных мониторов
# Документация: https://wiki.hypr.land/Configuring/Monitors/

monitor=,preferred,auto,auto
