# =============================================================================
# МОИ ПРОГРАММЫ
# =============================================================================
# Определение переменных для часто используемых программ
# Документация: https://wiki.hypr.land/Configuring/Keywords/

$terminal = ghostty
$fileManager = thunar
$menu = hyprlauncher
$browser = chromium
$code = code
$vpn = happ
$telegram = telegram-desktop
