# =============================================================================
# ГЛАВНЫЙ КОНФИГ HYPRLAND
# =============================================================================

# Подключение всех модулей из папки conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/permissions.conf
source = ~/.config/hypr/conf/look-and-feel.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/window-rules.conf
source = ~/.config/hypr/conf/gestures.conf

# =============================================================================
